"""Generate and check links between tagged architecture promises, code and tests."""

from __future__ import annotations

import argparse
import ast
import io
import re
import sys
import tokenize
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANCHOR = re.compile(r'^<a id="(IP[0-9]{4})"></a><!-- ([^<>]+) -->$')
MARKER = re.compile(r"# (Implements|Verifies): (.*)")
IDENTIFIERS = re.compile(r"IP[0-9]{4}(?:, IP[0-9]{4})*")
SHELL_FUNCTION = re.compile(r"([a-zA-Z_][a-zA-Z_0-9]*)\(\) \{")


@dataclass(frozen=True)
class Reference:
    path: str
    line: int
    function: str

    def link(self) -> str:
        return f"[{self.function}](../{self.path}#L{self.line})"


@dataclass
class Promise:
    title: str
    implementations: list[Reference] = field(default_factory=list)
    tests: list[Reference] = field(default_factory=list)


def references(path: Path) -> list[tuple[str, list[str], int, str]]:
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines()
    functions: dict[int, str] = {}
    if path.suffix == ".py":
        functions = {
            node.lineno: node.name
            for node in ast.walk(ast.parse(source))
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        }
        comments = [
            (token.start[0], token.string)
            for token in tokenize.generate_tokens(io.StringIO(source).readline)
            if token.type == tokenize.COMMENT
        ]
    else:
        comments = [(number, line.strip()) for number, line in enumerate(lines, 1)]
        functions = {
            number: match[1]
            for number, line in enumerate(lines, 1)
            if (match := SHELL_FUNCTION.fullmatch(line.strip()))
        }
    found = []
    for number, comment in comments:
        marker = MARKER.fullmatch(comment)
        if marker is None:
            continue
        if not IDENTIFIERS.fullmatch(marker[2]):
            raise ValueError(f"{path}:{number}: invalid promise IDs")
        identifiers = marker[2].split(", ")
        if len(set(identifiers)) != len(identifiers):
            raise ValueError(f"{path}:{number}: repeated promise ID")
        function = functions.get(number + 1)
        if function is None:
            raise ValueError(
                f"{path}:{number}: marker must immediately precede a function"
            )
        found.append((marker[1], identifiers, number + 1, function))
    return found


def render(root: Path) -> str:
    promises: dict[str, Promise] = {}
    for architecture_line in (
        (root / "ARCHITECTURE.md").read_text(encoding="utf-8").splitlines()
    ):
        if match := ANCHOR.fullmatch(architecture_line):
            if match[1] in promises:
                raise ValueError(f"duplicate architecture promise: {match[1]}")
            promises[match[1]] = Promise(match[2])
    if not promises:
        raise ValueError("no architecture promises found")
    for directory in ("generator", "scripts", "tests"):
        for path in sorted((root / directory).rglob("*")):
            if not path.is_file() or path.suffix not in {".py", ".sh"}:
                continue
            is_test = directory == "tests"
            for kind, identifiers, line, function in references(path):
                expected = "Verifies" if is_test else "Implements"
                if kind != expected or (
                    is_test
                    and (
                        not path.name.startswith("test_")
                        or not function.startswith("test_")
                    )
                ):
                    raise ValueError(f"{path}:{line}: invalid {kind} reference")
                for identifier in identifiers:
                    if identifier not in promises:
                        raise ValueError(f"{path}:{line}: unknown promise {identifier}")
                    promise = promises[identifier]
                    target = promise.tests if is_test else promise.implementations
                    target.append(
                        Reference(path.relative_to(root).as_posix(), line, function)
                    )
    output = [
        "# Implementation matrix",
        "",
        "Generated by `uv run python hack/implementation.py`. Do not edit manually.",
        "",
        "This indexes the tagged contracts in ARCHITECTURE.md. Untagged requirements",
        "still apply. Links establish traceability, not test coverage or qualification.",
        "",
    ]
    rows = [["Promise", "Production code", "Verification tests"]]
    for identifier, promise in sorted(promises.items()):
        if not promise.implementations or not promise.tests:
            raise ValueError(
                f"{identifier} needs production and verification references"
            )
        label = f"[{identifier}: {promise.title}](../ARCHITECTURE.md#{identifier})"
        code = ", ".join(reference.link() for reference in promise.implementations)
        tests = ", ".join(reference.link() for reference in promise.tests)
        rows.append([label, code, tests])
    # Align the committed table the way the Markdown rule set expects: every
    # column but the last padded to its widest cell, the header centered, and
    # the trailing column left ragged.
    last = len(rows[0]) - 1
    widths = [
        len(rows[0][column])
        if column == last
        else max(len(row[column]) for row in rows)
        for column in range(len(rows[0]))
    ]

    def row_line(cells: list[str], *, centered: bool = False) -> str:
        padded = []
        for column, cell in enumerate(cells):
            if column == last:
                padded.append(cell)
            elif centered:
                padded.append(cell.center(widths[column]))
            else:
                padded.append(cell.ljust(widths[column]))
        return "| " + " | ".join(padded) + " |"

    output.append(row_line(rows[0], centered=True))
    output.append("| " + " | ".join("-" * width for width in widths) + " |")
    output.extend(row_line(row) for row in rows[1:])
    return "\n".join(output) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    document = render(ROOT)
    output = ROOT / "docs/implementation.md"
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != document:
            raise ValueError(
                "implementation matrix is stale; run uv run python hack/implementation.py"
            )
    else:
        output.write_text(document, encoding="utf-8")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError, SyntaxError, tokenize.TokenError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from None
